services:
  db:
    image: mariadb:10.6
    container_name: SuiteCRM-DB
    hostname: suitecrm-db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=suitecrmuser
      - MARIADB_DATABASE=suitecrm
      - MARIADB_PASSWORD=suitecrmpass
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql:rw
    networks:
      - app-network
    restart: unless-stopped

  suitecrm:
    image: bitnamilegacy/suitecrm:8
    container_name: SuiteCRM
    ports:
      - "8200:8080"
      - "8443:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_DATABASE_HOST=db
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=suitecrmuser
      - SUITECRM_DATABASE_NAME=suitecrm
      - SUITECRM_DATABASE_PASSWORD=suitecrmpass
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=password123
      - SUITECRM_HOST=localhost
      - SUITECRM_ENABLE_HTTPS=no
      - SUITECRM_SKIP_BOOTSTRAP=no
    volumes:
      - suitecrm_data:/bitnami/suitecrm:rw
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    
  laravel:
    build:
      context: ./app-suitecrmtest 
      dockerfile: Dockerfile
    container_name: LaravelContactTalentum
    ports:
      - "8000:80"
    volumes:
      - ./app-suitecrmtest:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - SUITECRM_API_URL=http://suitecrm:8080/legacy/Api/V8/module/ 
    depends_on:
      - db
      - suitecrm
    networks:
      - app-network
    restart: unless-stopped
    command: >
        bash -c "
        composer install --no-interaction &&
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
        chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
        apache2-foreground"

volumes:
  db_data:
  suitecrm_data:

networks:
  app-network:
    driver: bridge